let a = Reaml_Core.element "a"
let animate = Reaml_Core.element "animate"
let animateColor = Reaml_Core.element "animateColor"
let animateMotion = Reaml_Core.element "animateMotion"
let animateTransform = Reaml_Core.element "animateTransform"
let circle = Reaml_Core.element "circle"
let clipPath = Reaml_Core.element "clipPath"
let colorProfile = Reaml_Core.element "color-profile"
let cursor = Reaml_Core.element "cursor"
let defs = Reaml_Core.element "defs"
let desc = Reaml_Core.element "desc"
let discard = Reaml_Core.element "discard"
let ellipse = Reaml_Core.element "ellipse"
let feBlend = Reaml_Core.element "feBlend"
let feColorMatrix = Reaml_Core.element "feColorMatrix"
let feComponentTransfer = Reaml_Core.element "feComponentTransfer"
let feComposite = Reaml_Core.element "feComposite"
let feConvolveMatrix = Reaml_Core.element "feConvolveMatrix"
let feDiffuseLighting = Reaml_Core.element "feDiffuseLighting"
let feDisplacementMap = Reaml_Core.element "feDisplacementMap"
let feDistantLight = Reaml_Core.element "feDistantLight"
let feDropShadow = Reaml_Core.element "feDropShadow"
let feFlood = Reaml_Core.element "feFlood"
let feFuncA = Reaml_Core.element "feFuncA"
let feFuncB = Reaml_Core.element "feFuncB"
let feFuncG = Reaml_Core.element "feFuncG"
let feFuncR = Reaml_Core.element "feFuncR"
let feGaussianBlur = Reaml_Core.element "feGaussianBlur"
let feImage = Reaml_Core.element "feImage"
let feMerge = Reaml_Core.element "feMerge"
let feMergeNode = Reaml_Core.element "feMergeNode"
let feMorphology = Reaml_Core.element "feMorphology"
let feOffset = Reaml_Core.element "feOffset"
let fePointLight = Reaml_Core.element "fePointLight"
let feSpecularLighting = Reaml_Core.element "feSpecularLighting"
let feSpotLight = Reaml_Core.element "feSpotLight"
let feTile = Reaml_Core.element "feTile"
let feTurbulence = Reaml_Core.element "feTurbulence"
let filter = Reaml_Core.element "filter"
let font = Reaml_Core.element "font"
let fontFace = Reaml_Core.element "font-face"
let fontFaceFormat = Reaml_Core.element "font-face-format"
let fontFaceName = Reaml_Core.element "font-face-name"
let fontFaceSrc = Reaml_Core.element "font-face-src"
let fontFaceUri = Reaml_Core.element "font-face-uri"
let foreignObject = Reaml_Core.element "foreignObject"
let g = Reaml_Core.element "g"
let glyph = Reaml_Core.element "glyph"
let glyphRef = Reaml_Core.element "glyphRef"
let hatch = Reaml_Core.element "hatch"
let hatchpath = Reaml_Core.element "hatchpath"
let hkern = Reaml_Core.element "hkern"
let image = Reaml_Core.element "image"
let line = Reaml_Core.element "line"
let linearGradient = Reaml_Core.element "linearGradient"
let marker = Reaml_Core.element "marker"
let mask = Reaml_Core.element "mask"
let mesh = Reaml_Core.element "mesh"
let meshgradient = Reaml_Core.element "meshgradient"
let meshpatch = Reaml_Core.element "meshpatch"
let meshrow = Reaml_Core.element "meshrow"
let metadata = Reaml_Core.element "metadata"
let missingGlyph = Reaml_Core.element "missing-glyph"
let mpath = Reaml_Core.element "mpath"
let path = Reaml_Core.element "path"
let pattern = Reaml_Core.element "pattern"
let polygon = Reaml_Core.element "polygon"
let polyline = Reaml_Core.element "polyline"
let radialGradient = Reaml_Core.element "radialGradient"
let rect = Reaml_Core.element "rect"
let script = Reaml_Core.element "script"
let set = Reaml_Core.element "set"
let solidcolor = Reaml_Core.element "solidcolor"
let stop = Reaml_Core.element "stop"
let style' = Reaml_Core.element "style"
let svg = Reaml_Core.element "svg"
let switch = Reaml_Core.element "switch"
let symbol = Reaml_Core.element "symbol"
let text = Reaml_Core.element "text"
let textPath = Reaml_Core.element "textPath"
let title = Reaml_Core.element "title"
let tref = Reaml_Core.element "tref"
let tspan = Reaml_Core.element "tspan"
let unknown = Reaml_Core.element "unknown"
let use = Reaml_Core.element "use"
let view = Reaml_Core.element "view"
let vkern = Reaml_Core.element "vkern"
let accentHeight (value : float) = Reaml_Core.property "accent-height" value
let accumulate (value : string) = Reaml_Core.property "accumulate" value
let additive (value : string) = Reaml_Core.property "additive" value
let alignmentBaseline (value : string) = Reaml_Core.property "alignment-baseline" value
let ascent (value : float) = Reaml_Core.property "ascent" value
let attributeName (value : string) = Reaml_Core.property "attributeName" value
let attributeType (value : string) = Reaml_Core.property "attributeType" value
let azimuth (value : float) = Reaml_Core.property "azimuth" value
let baseFrequency (value : string) = Reaml_Core.property "baseFrequency" value
let baseProfile (value : string) = Reaml_Core.property "baseProfile" value
let baselineShift (value : string) = Reaml_Core.property "baseline-shift" value
let begin' (value : string) = Reaml_Core.property "begin" value
let bias (value : float) = Reaml_Core.property "bias" value
let calcMode (value : string) = Reaml_Core.property "calcMode" value
let clipPath' (value : string) = Reaml_Core.property "clip-path" value
let clipRule (value : string) = Reaml_Core.property "clip-rule" value
let clipPathUnits (value : string) = Reaml_Core.property "clipPathUnits" value
let color (value : string) = Reaml_Core.property "color" value
let colorInterpolation (value : string) = Reaml_Core.property "color-interpolation" value

let colorInterpolationFilters (value : string) =
  Reaml_Core.property "color-interpolation-filters" value

let colorProfile' (value : string) = Reaml_Core.property "color-profile" value
let colorRendering (value : string) = Reaml_Core.property "color-rendering" value
let contentScriptType (value : string) = Reaml_Core.property "contentScriptType" value
let contentStyleType (value : string) = Reaml_Core.property "contentStyleType" value
let cursor' (value : string) = Reaml_Core.property "cursor" value
let cx (value : string) = Reaml_Core.property "cx" value
let cy (value : string) = Reaml_Core.property "cy" value
let d (value : string) = Reaml_Core.property "d" value
let diffuseConstant (value : float) = Reaml_Core.property "diffuseConstant" value
let direction (value : string) = Reaml_Core.property "direction" value
let display (value : string) = Reaml_Core.property "display" value
let divisor (value : float) = Reaml_Core.property "divisor" value
let dominantBaseline (value : string) = Reaml_Core.property "dominant-baseline" value
let dur (value : string) = Reaml_Core.property "dur" value
let dx (value : string) = Reaml_Core.property "dx" value
let dy (value : string) = Reaml_Core.property "dy" value
let edgeMode (value : string) = Reaml_Core.property "edgeMode" value
let elevation (value : float) = Reaml_Core.property "elevation" value
let end' (value : string) = Reaml_Core.property "end" value

let externalResourcesRequired (value : bool) =
  Reaml_Core.property "externalResourcesRequired" value

let fill (value : string) = Reaml_Core.property "fill" value
let fillOpacity (value : string) = Reaml_Core.property "fill-opacity" value
let fillRule (value : string) = Reaml_Core.property "fill-rule" value
let filter' (value : string) = Reaml_Core.property "filter" value
let filterUnits (value : string) = Reaml_Core.property "filterUnits" value
let floodColor (value : string) = Reaml_Core.property "flood-color" value
let floodOpacity (value : string) = Reaml_Core.property "flood-opacity" value
let fontFamily (value : string) = Reaml_Core.property "font-family" value
let fontSize (value : string) = Reaml_Core.property "font-size" value
let fontSizeAdjust (value : string) = Reaml_Core.property "font-size-adjust" value
let fontStretch (value : string) = Reaml_Core.property "font-stretch" value
let fontStyle (value : string) = Reaml_Core.property "font-style" value
let fontVariant (value : string) = Reaml_Core.property "font-variant" value
let fontWeight (value : string) = Reaml_Core.property "font-weight" value
let fr (value : float) = Reaml_Core.property "fr" value
let from (value : string) = Reaml_Core.property "from" value
let fx (value : string) = Reaml_Core.property "fx" value
let fy (value : string) = Reaml_Core.property "fy" value
let gradientTransform (value : string) = Reaml_Core.property "gradientTransform" value
let gradientUnits (value : string) = Reaml_Core.property "gradientUnits" value
let height (value : string) = Reaml_Core.property "height" value
let href (value : string) = Reaml_Core.property "href" value
let imageRendering (value : string) = Reaml_Core.property "image-rendering" value
let in' (value : string) = Reaml_Core.property "in" value
let in2 (value : string) = Reaml_Core.property "in2" value
let k1 (value : float) = Reaml_Core.property "k1" value
let k2 (value : float) = Reaml_Core.property "k2" value
let k3 (value : float) = Reaml_Core.property "k3" value
let k4 (value : float) = Reaml_Core.property "k4" value
let kernelMatrix (value : string) = Reaml_Core.property "kernelMatrix" value
let kernelUnitLength (value : string) = Reaml_Core.property "kernelUnitLength" value
let kerning (value : string) = Reaml_Core.property "kerning" value
let keySplines (value : string) = Reaml_Core.property "keySplines" value
let keyTimes (value : string) = Reaml_Core.property "keyTimes" value
let lengthAdjust (value : string) = Reaml_Core.property "lengthAdjust" value
let letterSpacing (value : string) = Reaml_Core.property "letter-spacing" value
let lightingColor (value : string) = Reaml_Core.property "lighting-color" value
let limitingConeAngle (value : float) = Reaml_Core.property "limitingConeAngle" value
let local (value : string) = Reaml_Core.property "local" value
let markerEnd (value : string) = Reaml_Core.property "marker-end" value
let markerMid (value : string) = Reaml_Core.property "marker-mid" value
let markerStart (value : string) = Reaml_Core.property "marker-start" value
let markerHeight (value : string) = Reaml_Core.property "markerHeight" value
let markerUnits (value : string) = Reaml_Core.property "markerUnits" value
let markerWidth (value : string) = Reaml_Core.property "markerWidth" value
let mask' (value : string) = Reaml_Core.property "mask" value
let maskContentUnits (value : string) = Reaml_Core.property "maskContentUnits" value
let maskUnits (value : string) = Reaml_Core.property "maskUnits" value
let max (value : string) = Reaml_Core.property "max" value
let min (value : string) = Reaml_Core.property "min" value
let mode (value : string) = Reaml_Core.property "mode" value
let numOctaves (value : int) = Reaml_Core.property "numOctaves" value
let opacity (value : string) = Reaml_Core.property "opacity" value
let operator (value : string) = Reaml_Core.property "operator" value
let order (value : string) = Reaml_Core.property "order" value
let overflow (value : string) = Reaml_Core.property "overflow" value
let overlinePosition (value : float) = Reaml_Core.property "overline-position" value
let overlineThickness (value : float) = Reaml_Core.property "overline-thickness" value
let paintOrder (value : string) = Reaml_Core.property "paint-order" value
let pathLength (value : float) = Reaml_Core.property "pathLength" value

let patternContentUnits (value : string) =
  Reaml_Core.property "patternContentUnits" value

let patternTransform (value : string) = Reaml_Core.property "patternTransform" value
let patternUnits (value : string) = Reaml_Core.property "patternUnits" value
let pointerEvents (value : string) = Reaml_Core.property "pointer-events" value
let points (value : string) = Reaml_Core.property "points" value
let pointsAtX (value : float) = Reaml_Core.property "pointsAtX" value
let pointsAtY (value : float) = Reaml_Core.property "pointsAtY" value
let pointsAtZ (value : float) = Reaml_Core.property "pointsAtZ" value
let preserveAlpha (value : bool) = Reaml_Core.property "preserveAlpha" value

let preserveAspectRatio (value : string) =
  Reaml_Core.property "preserveAspectRatio" value

let primitiveUnits (value : string) = Reaml_Core.property "primitiveUnits" value
let r (value : string) = Reaml_Core.property "r" value
let radius (value : string) = Reaml_Core.property "radius" value
let refX (value : float) = Reaml_Core.property "refX" value
let refY (value : float) = Reaml_Core.property "refY" value
let repeatCount (value : string) = Reaml_Core.property "repeatCount" value
let repeatDur (value : string) = Reaml_Core.property "repeatDur" value
let requiredFeatures (value : string) = Reaml_Core.property "requiredFeatures" value
let restart (value : string) = Reaml_Core.property "restart" value
let result (value : string) = Reaml_Core.property "result" value
let rx (value : string) = Reaml_Core.property "rx" value
let ry (value : string) = Reaml_Core.property "ry" value
let scale (value : float) = Reaml_Core.property "scale" value
let seed (value : float) = Reaml_Core.property "seed" value
let shapeRendering (value : string) = Reaml_Core.property "shape-rendering" value
let specularConstant (value : float) = Reaml_Core.property "specularConstant" value
let specularExponent (value : float) = Reaml_Core.property "specularExponent" value
let stdDeviation (value : string) = Reaml_Core.property "stdDeviation" value
let stitchTiles (value : string) = Reaml_Core.property "stitchTiles" value
let stopColor (value : string) = Reaml_Core.property "stop-color" value
let stopOpacity (value : string) = Reaml_Core.property "stop-opacity" value

let strikethroughPosition (value : float) =
  Reaml_Core.property "strikethrough-position" value

let strikethroughThickness (value : float) =
  Reaml_Core.property "strikethrough-thickness" value

let stroke (value : string) = Reaml_Core.property "stroke" value
let strokeDasharray (value : string) = Reaml_Core.property "stroke-dasharray" value
let strokeDashoffset (value : string) = Reaml_Core.property "stroke-dashoffset" value
let strokeLinecap (value : string) = Reaml_Core.property "stroke-linecap" value
let strokeLinejoin (value : string) = Reaml_Core.property "stroke-linejoin" value
let strokeMiterlimit (value : float) = Reaml_Core.property "stroke-miterlimit" value
let strokeOpacity (value : string) = Reaml_Core.property "stroke-opacity" value
let strokeWidth (value : string) = Reaml_Core.property "stroke-width" value
let surfaceScale (value : float) = Reaml_Core.property "surfaceScale" value
let tabindex (value : int) = Reaml_Core.property "tabindex" value
let targetX (value : float) = Reaml_Core.property "targetX" value
let targetY (value : float) = Reaml_Core.property "targetY" value
let textAnchor (value : string) = Reaml_Core.property "text-anchor" value
let textDecoration (value : string) = Reaml_Core.property "text-decoration" value
let textRendering (value : string) = Reaml_Core.property "text-rendering" value
let textLength (value : string) = Reaml_Core.property "textLength" value
let to' (value : string) = Reaml_Core.property "to" value
let transform (value : string) = Reaml_Core.property "transform" value
let type' (value : string) = Reaml_Core.property "type" value
let underlinePosition (value : float) = Reaml_Core.property "underline-position" value
let underlineThickness (value : float) = Reaml_Core.property "underline-thickness" value
let values (value : string) = Reaml_Core.property "values" value
let vectorEffect (value : string) = Reaml_Core.property "vector-effect" value
let version (value : float) = Reaml_Core.property "version" value
let viewBox (value : string) = Reaml_Core.property "viewBox" value
let visibility (value : string) = Reaml_Core.property "visibility" value
let width (value : string) = Reaml_Core.property "width" value
let wordSpacing (value : string) = Reaml_Core.property "word-spacing" value
let writingMode (value : string) = Reaml_Core.property "writing-mode" value
let x (value : string) = Reaml_Core.property "x" value
let x1 (value : string) = Reaml_Core.property "x1" value
let x2 (value : string) = Reaml_Core.property "x2" value
let xChannelSelector (value : string) = Reaml_Core.property "xChannelSelector" value
let y (value : string) = Reaml_Core.property "y" value
let y1 (value : string) = Reaml_Core.property "y1" value
let y2 (value : string) = Reaml_Core.property "y2" value
let yChannelSelector (value : string) = Reaml_Core.property "yChannelSelector" value
