#!/bin/bash

mkdir -p bin

get() {
  echo -n "Enter URL for $1: "
  read url
  curl -L $url > $1.zip
  unzip $1.zip -d tmp
  mv tmp/ppx.exe bin/$1.exe
  chmod +x bin/$1.exe
  rm -rf tmp
  rm $1.zip
}

get darwin-x64
get linux-x64
