#!/usr/bin/env ruby

require "json"
require "open-uri"

print "enter run id: "
run_id = gets.chomp
url = "https://api.github.com/repos/utkarshkukreti/reaml/actions/runs/#{run_id}/artifacts"
response = JSON.parse(open(url).read)
response["artifacts"].each do |artifact|
  name = case artifact["name"]
    when "macos-latest.exe" then "darwin-x64"
    when "ubuntu-latest.exe" then "linux-x64"
    when "windows-latest.exe" then "win-x64"
    else next
    end
  system "curl", "-u", "utkarshkukreti:#{ENV["GITHUB_TOKEN"]}", "-L", "-o", "#{name}.zip", artifact["archive_download_url"]
  system "unzip", "#{name}.zip", "-d", "tmp"
  system "mv", "tmp/Reaml_Ppx_Bin.exe", "bin/#{name}.exe"
  system "chmod", "+x", "bin/#{name}.exe"
  system "rm", "-rf", "tmp"
  system "rm", "#{name}.zip"
end
